In [122]:
import pandas as pd

Nettoyage du dataset

In [123]:
data = pd.read_csv('tractors_dataset.csv')

In [124]:
data.head()

,listing_id,manufacturer,price,location,Model:,Condition:,Location:,Listing ID:,Update:,Year of construction:,Mileage:
0,21468897,Kenworth,"$43,000 \r\n ...",Atlanta,W900L,ready for operation (used),"Atlanta, United States",A214-68-897,10.03.2026,NaN,NaN
1,21507582,Scania,"€57,174 \r\n ...",Norway,R730 6x4 Tractor Unit with Hydraulics and Rais...,used,Trøndelag,A215-07-582,15.03.2026,2016.0,"700,000 km"
2,21486682,Volvo,"€147,616 \r\n ...",Norway,FH 500 6x4 Tractor w/ 2024 Rojo Tipper Semi,used,Nord-Trøndelag,A214-86-682,12.03.2026,2021.0,"320,000 km"
3,21140282,MAN,"€34,823 \r\n ...",Norway,TGX 33.500 6x4 Tractor Unit,used,Akershus,A211-40-282,12.03.2026,2017.0,"132,225 km"
4,21508207,MAN,"€16,950 \r\n ...",Vuren,18.400 TGX HYDRODRIVE,good (used),"Vuren, The Netherlands",A215-08-207,14.03.2026,2014.0,"688,102 km"

Retirer les ":" au niveau des noms de colonnes

In [125]:
data_cleaned = data.copy()
data_cleaned["Model"] = data_cleaned["Model:"]
data_cleaned["Condition"] = data_cleaned["Condition:"]
data_cleaned["Location"] = data_cleaned["Location:"]
data_cleaned["Listing ID"] = data_cleaned["Listing ID:"]
data_cleaned["Update"] = data_cleaned["Update:"]
data_cleaned["Year of construction"] = data_cleaned["Year of construction:"]
data_cleaned["Mileage"] = data_cleaned["Mileage:"]
# retirer les anciennes colonnes
data_cleaned.drop(columns=["Model:", "Condition:", "Location:", "Listing ID:", "Update:", "Year of construction:", "Mileage:"], inplace=True)

In [126]:
data_cleaned.head()

,listing_id,manufacturer,price,location,Model,Condition,Location,Listing ID,Update,Year of construction,Mileage
0,21468897,Kenworth,"$43,000 \r\n ...",Atlanta,W900L,ready for operation (used),"Atlanta, United States",A214-68-897,10.03.2026,NaN,NaN
1,21507582,Scania,"€57,174 \r\n ...",Norway,R730 6x4 Tractor Unit with Hydraulics and Rais...,used,Trøndelag,A215-07-582,15.03.2026,2016.0,"700,000 km"
2,21486682,Volvo,"€147,616 \r\n ...",Norway,FH 500 6x4 Tractor w/ 2024 Rojo Tipper Semi,used,Nord-Trøndelag,A214-86-682,12.03.2026,2021.0,"320,000 km"
3,21140282,MAN,"€34,823 \r\n ...",Norway,TGX 33.500 6x4 Tractor Unit,used,Akershus,A211-40-282,12.03.2026,2017.0,"132,225 km"
4,21508207,MAN,"€16,950 \r\n ...",Vuren,18.400 TGX HYDRODRIVE,good (used),"Vuren, The Netherlands",A215-08-207,14.03.2026,2014.0,"688,102 km"

Nettoyage de la colonne price

In [127]:
data_cleaned["price"].unique()

array(['$43,000                            \r\n         ONO plus VAT',
       '€57,174                            \r\n         Fixed price plus VAT        \r\n        (€71,468 gross)',
       '€147,616                            \r\n         Fixed price plus VAT        \r\n        (€184,520 gross)',
       '€34,823                            \r\n                                            €38,110                                    \r\n         Fixed price plus VAT        \r\n        (€43,529 gross)',
       '€16,950                            \r\n         ONO plus VAT        \r\n        (€20,510 gross)',
       '€92,900                            \r\n         ONO plus VAT        \r\n        (€112,409 gross)',
       '€55,900                            \r\n         ONO plus VAT        \r\n        (€67,639 gross)',
       '€14,900                            \r\n         ONO plus VAT        \r\n        (€18,029 gross)',
       '€18,900                            \r\n         ONO plus VAT        \r\n        (€22,869 gross)',
       '€39,950                            \r\n         ONO plus VAT        \r\n        (€48,340 gross)',
       '€15,950                            \r\n         ONO plus VAT        \r\n        (€19,300 gross)',
       '€19,950                            \r\n         ONO plus VAT        \r\n        (€24,140 gross)',
       '€12,950                            \r\n         ONO plus VAT        \r\n        (€15,670 gross)',
       '€37,400                            \r\n                                            €38,900                                    \r\n         Fixed price plus VAT        \r\n        (€45,254 gross)',
       '€58,900                            \r\n         Fixed price plus VAT        \r\n        (€71,269 gross)',
       '€46,900                            \r\n         Fixed price plus VAT        \r\n        (€56,749 gross)',
       '€85,400                            \r\n         Fixed price plus VAT        \r\n        (€103,334 gross)',
       '€17,900                            \r\n         Fixed price plus VAT        \r\n        (€21,659 gross)',
       '€165,000                            \r\n         Fixed price plus VAT        \r\n        (€199,650 gross)',
       '€27,950                            \r\n         ONO plus VAT        \r\n        (€33,820 gross)',
       '€10,950                            \r\n                                            €11,950                                    \r\n         ONO plus VAT        \r\n        (€13,250 gross)',
       '€48,900                            \r\n         ONO plus VAT        \r\n        (€59,169 gross)',
       '€10,900                            \r\n         ONO plus VAT        \r\n        (€13,189 gross)',
       '€20,950                            \r\n         ONO plus VAT        \r\n        (€25,350 gross)',
       '€29,400                            \r\n         Fixed price plus VAT        \r\n        (€35,574 gross)',
       '€49,900                            \r\n         Fixed price plus VAT        \r\n        (€60,379 gross)',
       '€30,900                            \r\n         Fixed price plus VAT        \r\n        (€37,389 gross)',
       '€32,400                            \r\n         Fixed price plus VAT        \r\n        (€39,204 gross)',
       '€41,900                            \r\n         Fixed price plus VAT        \r\n        (€50,699 gross)',
       '€41,400                            \r\n         Fixed price plus VAT        \r\n        (€50,094 gross)',
       '€56,600                            \r\n         Fixed price plus VAT        \r\n        (€68,486 gross)',
       '€64,800                            \r\n         Fixed price plus VAT        \r\n        (€78,408 gross)',
       '€69,500                            \r\n         Fixed price plus VAT        \r\n        (€84,095 gross)',
       '€31,900                            \r\n         Fixed price plus VAT        \r\n        (€38,599 gross)',
       '€31,400                            \r\n         Fixed price plus VAT        \r\n        (€37,994 gross)',
       '€64,900                            \r\n         ONO plus VAT        \r\n        (€78,529 gross)',
       '€128,900                            \r\n         Fixed price plus VAT        \r\n        (€155,969 gross)',
       '€120,900                            \r\n         Fixed price plus VAT        \r\n        (€146,289 gross)',
       '€14,900                            \r\n         Fixed price plus VAT        \r\n        (€17,731 gross)',
       '€10,950                            \r\n         ONO plus VAT        \r\n        (€13,250 gross)',
       '€23,950                            \r\n         ONO plus VAT        \r\n        (€28,980 gross)',
       '€21,900                            \r\n         ONO plus VAT        \r\n        (€26,499 gross)',
       '€29,900                            \r\n         ONO plus VAT        \r\n        (€36,179 gross)',
       '€94,900                            \r\n         ONO plus VAT        \r\n        (€114,829 gross)',
       '€45,400                            \r\n         Fixed price plus VAT        \r\n        (€54,026 gross)',
       '€33,900                            \r\n         Fixed price plus VAT        \r\n        (€40,341 gross)',
       '€52,900                            \r\n         Fixed price plus VAT        \r\n        (€62,951 gross)',
       '€82,900                            \r\n         Fixed price plus VAT        \r\n        (€98,651 gross)',
       '€81,900                            \r\n         Fixed price plus VAT        \r\n        (€97,461 gross)',
       '€28,900                            \r\n         Fixed price plus VAT        \r\n        (€34,969 gross)',
       '€124,900                            \r\n         Fixed price plus VAT        \r\n        (€151,129 gross)',
       '€107,900                            \r\n         Fixed price plus VAT        \r\n        (€130,559 gross)',
       '€28,900                            \r\n         Fixed price plus VAT        \r\n        (€34,391 gross)',
       '€34,400                            \r\n         Fixed price plus VAT        \r\n        (€41,624 gross)',
       '€37,400                            \r\n         Fixed price plus VAT        \r\n        (€45,254 gross)',
       '€12,900                            \r\n         Fixed price plus VAT        \r\n        (€15,609 gross)',
       '€79,900                            \r\n         Fixed price plus VAT        \r\n        (€96,679 gross)',
       '€16,900                            \r\n         Fixed price plus VAT        \r\n        (€20,449 gross)',
       '€22,850                            \r\n         Fixed price plus VAT        \r\n        (€27,648 gross)',
       '€54,900                            \r\n         Fixed price plus VAT        \r\n        (€66,429 gross)',
       '€18,900                            \r\n         Fixed price plus VAT        \r\n        (€22,869 gross)',
       '€195,331                            \r\n         Fixed price plus VAT        \r\n        (€244,164 gross)',
       '€8,900                            \r\n                                            €9,400                                    \r\n         Fixed price plus VAT        \r\n        (€10,769 gross)',
       '€23,750                            \r\n         ONO plus VAT        \r\n        (€28,738 gross)',
       '€53,900                            \r\n         ONO plus VAT        \r\n        (€65,219 gross)',
       '€17,900                            \r\n         ONO plus VAT        \r\n        (€21,659 gross)',
       '€26,900                            \r\n         ONO plus VAT        \r\n        (€32,549 gross)',
       '€39,900                            \r\n         ONO plus VAT        \r\n        (€48,279 gross)',
       '€45,900                            \r\n         Fixed price plus VAT        \r\n        (€55,539 gross)',
       '€36,400                            \r\n         Fixed price plus VAT        \r\n        (€44,044 gross)',
       '€22,900                            \r\n         Fixed price plus VAT        \r\n        (€27,709 gross)',
       '€20,400                            \r\n         Fixed price plus VAT        \r\n        (€24,684 gross)',
       '€32,900                            \r\n         Fixed price plus VAT        \r\n        (€39,809 gross)',
       '€19,800                            \r\n                                            €20,400                                    \r\n         Fixed price plus VAT        \r\n        (€23,958 gross)',
       '€7,900                            \r\n                                            €8,700                                    \r\n         Fixed price plus VAT        \r\n        (€9,559 gross)',
       '€57,400                            \r\n         Fixed price plus VAT        \r\n        (€69,454 gross)',
       '€24,900                            \r\n         Fixed price plus VAT        \r\n        (€30,129 gross)',
       '€38,900                            \r\n         Fixed price plus VAT        \r\n        (€47,069 gross)',
       '€44,900                            \r\n         Fixed price plus VAT        \r\n        (€53,431 gross)',
       '€28,400                            \r\n         Fixed price plus VAT        \r\n        (€34,364 gross)',
       '€19,900                            \r\n         Fixed price plus VAT        \r\n        (€24,079 gross)',
       '€12,400                            \r\n         Fixed price plus VAT        \r\n        (€15,004 gross)',
       '€39,800                            \r\n         Fixed price plus VAT        \r\n        (€48,158 gross)',
       '€154,900                            \r\n         Fixed price plus VAT        \r\n        (€187,429 gross)',
       '€174,900                            \r\n         Fixed price plus VAT        \r\n        (€211,629 gross)',
       '€46,500                            \r\n         Fixed price plus VAT        \r\n        (€56,265 gross)',
       '€21,400                            \r\n         Fixed price plus VAT        \r\n        (€25,894 gross)',
       '€19,500                            \r\n         Fixed price plus VAT        \r\n        (€23,595 gross)',
       '€30,196                            \r\n         Fixed price plus VAT        \r\n        (€37,745 gross)',
       '€30,400                            \r\n         Fixed price plus VAT        \r\n        (€36,784 gross)',
       '€62,263                            \r\n         Fixed price plus VAT        \r\n        (€77,829 gross)',
       '€49,900                            \r\n         Fixed price plus VAT        \r\n        (€59,381 gross)',
       '€11,950                            \r\n         ONO plus VAT        \r\n        (€14,460 gross)',
       '€69,900                            \r\n         ONO plus VAT        \r\n        (€84,579 gross)',
       '€35,900                            \r\n         Fixed price plus VAT        \r\n        (€42,721 gross)',
       '€99,900                            \r\n         Fixed price plus VAT        \r\n        (€120,879 gross)',
       '€9,300                            \r\n         Fixed price plus VAT        \r\n        (€11,253 gross)',
       '€40,500                            \r\n         Fixed price plus VAT        \r\n        (€49,005 gross)',
       '€13,900                            \r\n         Fixed price plus VAT        \r\n        (€16,819 gross)',
       '€15,900                            \r\n         Fixed price plus VAT        \r\n        (€19,239 gross)',
       '€20,900                            \r\n         Fixed price plus VAT        \r\n        (€25,289 gross)',
       '€50,900                            \r\n         Fixed price plus VAT        \r\n        (€61,589 gross)',
       '€72,400                            \r\n         Fixed price plus VAT        \r\n        (€87,604 gross)',
       '€93,778                            \r\n         Fixed price plus VAT        \r\n        (€117,222 gross)',
       '€67,000                            \r\n         Fixed price plus VAT        \r\n        (€81,070 gross)',
       '€33,900                            \r\n         Fixed price plus VAT        \r\n        (€41,019 gross)',
       '€34,900                            \r\n         Fixed price plus VAT        \r\n        (€42,229 gross)',
       '€17,400                            \r\n         Fixed price plus VAT        \r\n        (€21,054 gross)',
       '€77,500                            \r\n         Fixed price plus VAT        \r\n        (€93,775 gross)',
       '€63,900                            \r\n         Fixed price plus VAT        \r\n        (€77,319 gross)',
       '€68,900                            \r\n         Fixed price plus VAT        \r\n        (€83,369 gross)',
       '€9,900                            \r\n                                            €10,700                                    \r\n         Fixed price plus VAT        \r\n        (€11,979 gross)',
       '€36,500                            \r\n         Fixed price plus VAT        \r\n        (€44,165 gross)',
       '€19,900                            \r\n         ONO plus VAT        \r\n        (€24,079 gross)',
       '€49,950                            \r\n         ONO plus VAT        \r\n        (€60,440 gross)',
       '€51,900                            \r\n         Fixed price plus VAT        \r\n        (€62,799 gross)',
       '€14,900                            \r\n         Fixed price plus VAT        \r\n        (€18,029 gross)',
       '€21,900                            \r\n         Fixed price plus VAT        \r\n        (€26,499 gross)',
       '€29,900                            \r\n         Fixed price plus VAT        \r\n        (€36,179 gross)',
       '€45,400                            \r\n         Fixed price plus VAT        \r\n        (€54,934 gross)',
       '€59,000                            \r\n         Fixed price plus VAT        \r\n        (€71,390 gross)',
       '€9,400                            \r\n         Fixed price plus VAT        \r\n        (€11,374 gross)',
       '€22,400                            \r\n         Fixed price plus VAT        \r\n        (€27,104 gross)',
       '€66,400                            \r\n         Fixed price plus VAT        \r\n        (€79,016 gross)',
       '€53,800                            \r\n         Fixed price plus VAT        \r\n        (€64,022 gross)',
       '€39,400                            \r\n         Fixed price plus VAT        \r\n        (€47,674 gross)',
       '€52,800                            \r\n         Fixed price plus VAT        \r\n        (€63,888 gross)',
       '€71,300                            \r\n         Fixed price plus VAT        \r\n        (€86,273 gross)',
       '€73,800                            \r\n         Fixed price plus VAT        \r\n        (€89,298 gross)',
       '€75,400                            \r\n         Fixed price plus VAT        \r\n        (€91,234 gross)',
       '€71,000                            \r\n         Fixed price plus VAT        \r\n        (€85,910 gross)',
       '€24,900                            \r\n         Fixed price plus VAT        \r\n        (€29,631 gross)',
       '€21,950                            \r\n         ONO plus VAT        \r\n        (€26,560 gross)',
       '€66,300                            \r\n         Fixed price plus VAT        \r\n        (€80,223 gross)',
       '€63,890                            \r\n                                            €65,890                                    \r\n         Fixed price plus VAT        \r\n        (€76,029 gross)',
       '€48,990                            \r\n         Fixed price plus VAT        \r\n        (€58,298 gross)',
       '€36,017                            \r\n         Fixed price plus VAT        \r\n        (€42,860 gross)',
       '€44,900                            \r\n         Fixed price plus VAT        \r\n        (€54,329 gross)',
       '€11,900                            \r\n         Fixed price plus VAT        \r\n        (€14,399 gross)',
       '€9,900                            \r\n         Fixed price plus VAT        \r\n        (€11,979 gross)',
       '€34,800                            \r\n         Fixed price plus VAT        \r\n        (€42,108 gross)'],
      dtype=object)

In [128]:
data_cleaned.shape

(200, 11)

In [129]:
prix_affiche = (data_cleaned['price'].str.replace('€', '').str.replace('$', '').str.strip().str.split(' ').str[0])
#
data_cleaned['prix_affiche'] = pd.to_numeric(prix_affiche.str.replace(',', ''), errors='coerce')

# Affichage pour vérifier
data_cleaned['prix_affiche'].head()

0     43000
1     57174
2    147616
3     34823
4     16950
Name: prix_affiche, dtype: int64

In [130]:
data_cleaned.drop(columns=["price"], inplace=True)

In [131]:
data_cleaned

,listing_id,manufacturer,location,Model,Condition,Location,Listing ID,Update,Year of construction,Mileage,prix_affiche
0,21468897,Kenworth,Atlanta,W900L,ready for operation (used),"Atlanta, United States",A214-68-897,10.03.2026,NaN,NaN,43000
1,21507582,Scania,Norway,R730 6x4 Tractor Unit with Hydraulics and Rais...,used,Trøndelag,A215-07-582,15.03.2026,2016.0,"700,000 km",57174
2,21486682,Volvo,Norway,FH 500 6x4 Tractor w/ 2024 Rojo Tipper Semi,used,Nord-Trøndelag,A214-86-682,12.03.2026,2021.0,"320,000 km",147616
3,21140282,MAN,Norway,TGX 33.500 6x4 Tractor Unit,used,Akershus,A211-40-282,12.03.2026,2017.0,"132,225 km",34823
4,21508207,MAN,Vuren,18.400 TGX HYDRODRIVE,good (used),"Vuren, The Netherlands",A215-08-207,14.03.2026,2014.0,"688,102 km",16950
...,...,...,...,...,...,...,...,...,...,...,...
195,21451052,Volvo,Veghel,FH 460 4X2 ADR Retarder VEB+ Alcoa's,used,"Veghel, Netherlands",A214-51-052,10.03.2026,2020.0,"693,581 km",44900
196,21451037,DAF,Veghel,XF 530 4X2 SSC Retarder 2xTanks Full-Air Stand...,used,"Veghel, Netherlands",A214-51-037,13.03.2026,2021.0,"604,093 km",30900
197,21451032,Volvo,Veghel,FM 340 FM 4X2 NL-Truck VEB Euro 3,used,"Veghel, Netherlands",A214-51-032,07.03.2026,2005.0,"654,924 km",11900
198,21451017,DAF,Veghel,XF 480 4X2 SC Hydraulik,used,"Veghel, Netherlands",A214-51-017,10.03.2026,2019.0,"887,848 km",9900
199,21451007,MAN,Veghel,TGX 18.510 4X2 GX Retarder ACC Standklima,used,"Veghel, Netherlands",A214-51-007,09.03.2026,2020.0,"486,383 km",34800

In [132]:
data_cleaned["location"].unique()

array(['Atlanta', 'Norway', 'Vuren', 'Veghel', 'Heteren', 'Viersen',
       'Dortmund', 'Madrid', 'Sittensen', 'Nordland', 'Sagunto',
       'Lichtenfels', 'Eilenburg'], dtype=object)

In [133]:
data_cleaned["Location"].unique()

array(['Atlanta, United States', 'Trøndelag', 'Nord-Trøndelag',
       'Akershus', 'Vuren, The Netherlands', 'Veghel, Netherlands',
       'Vuren, Netherlands', nan, 'Dortmund, Germany', 'Madrid, Spain',
       'Nordland', 'Buskerud', 'Vest-Agder', 'Sør-Trøndelag'],
      dtype=object)

In [134]:
data_cleaned["ville"] = data_cleaned["location"].astype(str)
data_cleaned.drop(columns=["location"], inplace=True)
data_cleaned["pays"] = data_cleaned["Location"].str.split(',').str[-1].str.strip()
data_cleaned.drop(columns=["Location"], inplace=True)

In [135]:
data_cleaned["pays"].unique()

array(['United States', 'Trøndelag', 'Nord-Trøndelag', 'Akershus',
       'The Netherlands', 'Netherlands', nan, 'Germany', 'Spain',
       'Nordland', 'Buskerud', 'Vest-Agder', 'Sør-Trøndelag'],
      dtype=object)

In [136]:
data_cleaned["pays"] = data_cleaned["pays"].str.replace('The Netherlands', 'Netherlands')

In [137]:
data_cleaned["pays"].unique()

array(['United States', 'Trøndelag', 'Nord-Trøndelag', 'Akershus',
       'Netherlands', nan, 'Germany', 'Spain', 'Nordland', 'Buskerud',
       'Vest-Agder', 'Sør-Trøndelag'], dtype=object)

Gestion des valeurs manquantes

In [138]:
data_cleaned.isnull().sum()

listing_id               0
manufacturer             0
Model                    0
Condition                0
Listing ID               0
Update                   0
Year of construction     5
Mileage                  1
prix_affiche             0
ville                    0
pays                    22
dtype: int64

In [139]:
mapping_villes_pays = {
    'Atlanta': 'United States',
    'Norway': None,           # "Norway" est un pays, aucune région norvégienne de votre liste ne correspond spécifiquement
    'Vuren': 'Netherlands',
    'Veghel': 'Netherlands',
    'Heteren': 'Netherlands',
    'Viersen': 'Germany',
    'Dortmund': 'Germany',
    'Madrid': 'Spain',
    'Sittensen': 'Germany',
    'Nordland': 'Nordland',   # Présent à la fois dans la liste des villes et des régions
    'Sagunto': 'Spain',
    'Lichtenfels': 'Germany',
    'Eilenburg': 'Germany'
}

In [140]:
data_cleaned['pays'] = data_cleaned['pays'].fillna(data_cleaned['ville'].map(mapping_villes_pays))

In [141]:
data_cleaned.isnull().sum()

listing_id              0
manufacturer            0
Model                   0
Condition               0
Listing ID              0
Update                  0
Year of construction    5
Mileage                 1
prix_affiche            0
ville                   0
pays                    0
dtype: int64

In [142]:
#convertir en entier
data_cleaned["Year of construction"] = data_cleaned["Year of construction"].astype('Int64')
#retirer km et convertir en float
data_cleaned["Mileage"] = data_cleaned["Mileage"].str.replace(' km', '').str.replace(',', '').astype('Int64')

In [143]:
data_cleaned["Mileage"].unique()

<IntegerArray>
[  <NA>, 700000, 320000, 132225, 688102, 740932, 708608, 296872, 391152,
 641098,
 ...
 321798, 299355, 296117, 165114, 735490, 693581, 604093, 654924, 887848,
 486383]
Length: 197, dtype: Int64

In [144]:
#data_cleaned["Mileage"].fillna(0, inplace=True)

In [145]:
data_cleaned["Update"] = pd.to_datetime(data_cleaned['Update'], format='%d.%m.%Y', errors='coerce')

In [146]:
data_cleaned.head()

,listing_id,manufacturer,Model,Condition,Listing ID,Update,Year of construction,Mileage,prix_affiche,ville,pays
0,21468897,Kenworth,W900L,ready for operation (used),A214-68-897,2026-03-10,<NA>,<NA>,43000,Atlanta,United States
1,21507582,Scania,R730 6x4 Tractor Unit with Hydraulics and Rais...,used,A215-07-582,2026-03-15,2016,700000,57174,Norway,Trøndelag
2,21486682,Volvo,FH 500 6x4 Tractor w/ 2024 Rojo Tipper Semi,used,A214-86-682,2026-03-12,2021,320000,147616,Norway,Nord-Trøndelag
3,21140282,MAN,TGX 33.500 6x4 Tractor Unit,used,A211-40-282,2026-03-12,2017,132225,34823,Norway,Akershus
4,21508207,MAN,18.400 TGX HYDRODRIVE,good (used),A215-08-207,2026-03-14,2014,688102,16950,Vuren,Netherlands

In [147]:
data_cleaned.dtypes

listing_id                       int64
manufacturer                    object
Model                           object
Condition                       object
Listing ID                      object
Update                  datetime64[ns]
Year of construction             Int64
Mileage                          Int64
prix_affiche                     int64
ville                           object
pays                            object
dtype: object

In [148]:
data_cleaned.isnull().sum()

listing_id              0
manufacturer            0
Model                   0
Condition               0
Listing ID              0
Update                  0
Year of construction    5
Mileage                 1
prix_affiche            0
ville                   0
pays                    0
dtype: int64

Afficher les lignes manquantes

In [152]:
data_cleaned[data_cleaned.isna().any(axis=1)]

,listing_id,manufacturer,Model,Condition,Listing ID,Update,Year of construction,Mileage,prix_affiche,ville,pays
0,21468897,Kenworth,W900L,ready for operation (used),A214-68-897,2026-03-10,<NA>,<NA>,43000,Atlanta,United States
65,21506277,MAN,"18.500 TGX 4x2, Intarder, Voll-Luft, Hydr.,Klima",used,A215-06-277,2026-03-14,<NA>,432700,28900,Sittensen,Germany
66,21506252,MAN,"18.500 TGX 4x2, Intarder, Voll-Luft, Hydr.,Klima",used,A215-06-252,2026-03-14,<NA>,443072,28900,Sittensen,Germany
96,21494907,MAN,"18.500 TGX 4X4, HydroDrive, Luft, Hydr., Klima",used,A214-94-907,2026-03-13,<NA>,281932,44900,Sittensen,Germany
193,21495012,FORD,F-Max Sattelzugmaschine,used,A214-95-012,2026-03-13,<NA>,165114,36017,Eilenburg,Germany

Nous avons 5 lignes concernées où il manque l'information de l'année de Construction. Nous demandons au contrôle qualité la marche à suivre pour gerer ces valeurs manquantes